import type { NearbyGym } from "./types";

export const MOCK_NEARBY_GYMS: NearbyGym[] = [
  {
    id: "gym-1",
    name: "Iron Fist MMA Academy",
    address: "123 Fighter Way, Los Angeles, CA",
    distance: 0.8,
    disciplines: ["MMA", "Boxing", "Muay Thai", "BJJ"],
    rating: 4.8,
    reviewCount: 127,
    isGymOpsPartner: true,
    isOpen: true,
    phone: "(555) 123-4567",
    website: "https://ironfistmma.com",
    latitude: 34.0522,
    longitude: -118.2437,
    logo: null,
  },
  {
    id: "gym-2",
    name: "Apex Boxing Club",
    address: "456 Champion Ave, Los Angeles, CA",
    distance: 1.2,
    disciplines: ["Boxing", "Kickboxing"],
    rating: 4.6,
    reviewCount: 89,
    isGymOpsPartner: true,
    isOpen: true,
    phone: "(555) 234-5678",
    website: "https://apexboxing.com",
    latitude: 34.0548,
    longitude: -118.2501,
    logo: null,
  },
  {
    id: "gym-3",
    name: "Warrior BJJ",
    address: "789 Grappler St, Los Angeles, CA",
    distance: 2.4,
    disciplines: ["BJJ", "Wrestling", "Judo"],
    rating: 4.9,
    reviewCount: 203,
    isGymOpsPartner: false,
    isOpen: false,
    phone: "(555) 345-6789",
    website: null,
    latitude: 34.0611,
    longitude: -118.238,
    logo: null,
  },
  {
    id: "gym-4",
    name: "Elite Muay Thai",
    address: "321 Strike Lane, Los Angeles, CA",
    distance: 3.1,
    disciplines: ["Muay Thai", "Kickboxing"],
    rating: 4.5,
    reviewCount: 64,
    isGymOpsPartner: true,
    isOpen: true,
    phone: "(555) 456-7890",
    website: "https://elitemuaythai.com",
    latitude: 34.0412,
    longitude: -118.2615,
    logo: null,
  },
  {
    id: "gym-5",
    name: "Champion Wrestling Academy",
    address: "654 Takedown Blvd, Los Angeles, CA",
    distance: 4.8,
    disciplines: ["Wrestling", "MMA"],
    rating: 4.7,
    reviewCount: 156,
    isGymOpsPartner: false,
    isOpen: true,
    phone: "(555) 567-8901",
    website: "https://championwrestling.com",
    latitude: 34.0688,
    longitude: -118.2295,
    logo: null,
  },
];

export const DISCIPLINES = [
  "MMA",
  "Boxing",
  "Muay Thai",
  "BJJ",
  "Wrestling",
  "Kickboxing",
  "Judo",
];

export const RADIUS_OPTIONS = [2, 5, 10, 25, 50];
